### ISSUE TITLE
Issue with release v3.1.0

### ISSUE THREAD

**Issue by evchristelis** [cti-nts/keycloak-gsis-providers#73]
We tried to deploy the latest release (v3.1.0) but we got the following errors.
Can you advise?

`Updating the configuration and installing your custom providers, if any. Please wait.

2024-10-25 08:08:30,346 WARN  [org.key.services] (build-6) KC-SERVICES0047: gsis-user-attribute-mapper (gr.cti.nts.keycloak.idp.social.gsis.GsisUserAttributeMapper) is implementing the internal SPI identity-provider-mapper. This SPI is internal and may change without notice

2024-10-25 08:08:30,628 WARN  [org.key.services] (build-6) KC-SERVICES0047: gsis-taxis (gr.cti.nts.keycloak.idp.social.gsis.GsisTaxisIdentityProviderFactory) is implementing the internal SPI social. This SPI is internal and may change without notice

2024-10-25 08:08:30,628 WARN  [org.key.services] (build-6) KC-SERVICES0047: gsis-taxis-test (gr.cti.nts.keycloak.idp.social.gsis.GsisTaxisTestIdentityProviderFactory) is implementing the internal SPI social. This SPI is internal and may change without notice

2024-10-25 08:08:30,628 WARN  [org.key.services] (build-6) KC-SERVICES0047: gsis-govuser (gr.cti.nts.keycloak.idp.social.gsis.GsisGovuserIdentityProviderFactory) is implementing the internal SPI social. This SPI is internal and may change without notice

2024-10-25 08:08:30,628 WARN  [org.key.services] (build-6) KC-SERVICES0047: gsis-govuser-test (gr.cti.nts.keycloak.idp.social.gsis.GsisGovuserTestIdentityProviderFactory) is implementing the internal SPI social. This SPI is internal and may change without notice

ERROR: Failed to run 'build' command.

ERROR: io.quarkus.builder.BuildException: Build failure: Build failed due to errors

	[error]: Build step io.quarkus.resteasy.reactive.server.deployment.ResteasyReactiveProcessor#setupEndpoints threw an exception: java.lang.RuntimeException: jakarta.enterprise.inject.spi.DeploymentException: Non static nested resources classes are not supported: 'gr.cti.nts.keycloak.idp.social.gsis.GsisAbstractIdentityProvider$OIDCEndpoint'

	at org.jboss.resteasy.reactive.common.processor.EndpointIndexer.createEndpoints(EndpointIndexer.java:333)

	at io.quarkus.resteasy.reactive.server.deployment.ResteasyReactiveProcessor.setupEndpoints(ResteasyReactiveProcessor.java:720)

	at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:733)

	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:856)

	at io.quarkus.builder.BuildContext.run(BuildContext.java:256)

	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)

	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)

	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)

	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)

	at java.base/java.lang.Thread.run(Thread.java:1583)

	at org.jboss.threads.JBossThread.run(JBossThread.java:483)

Caused by: jakarta.enterprise.inject.spi.DeploymentException: Non static nested resources classes are not supported: 'gr.cti.nts.keycloak.idp.social.gsis.GsisAbstractIdentityProvider$OIDCEndpoint'

	at org.jboss.resteasy.reactive.common.processor.EndpointIndexer.createEndpoints(EndpointIndexer.java:281)


	... 10 more

ERROR: Build failure: Build failed due to errors

	[error]: Build step io.quarkus.resteasy.reactive.server.deployment.ResteasyReactiveProcessor#setupEndpoints threw an exception: java.lang.RuntimeException: jakarta.enterprise.inject.spi.DeploymentException: Non static nested resources classes are not supported: 'gr.cti.nts.keycloak.idp.social.gsis.GsisAbstractIdentityProvider$OIDCEndpoint'

	at org.jboss.resteasy.reactive.common.processor.EndpointIndexer.createEndpoints(EndpointIndexer.java:333)

	at io.quarkus.resteasy.reactive.server.deployment.ResteasyReactiveProcessor.setupEndpoints(ResteasyReactiveProcessor.java:720)

	at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:733)

	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:856)

	at io.quarkus.builder.BuildContext.run(BuildContext.java:256)

	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)

	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)

	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)

	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)

	at java.base/java.lang.Thread.run(Thread.java:1583)

	at org.jboss.threads.JBossThread.run(JBossThread.java:483)

Caused by: jakarta.enterprise.inject.spi.DeploymentException: Non static nested resources classes are not supported: 'gr.cti.nts.keycloak.idp.social.gsis.GsisAbstractIdentityProvider$OIDCEndpoint'

	at org.jboss.resteasy.reactive.common.processor.EndpointIndexer.createEndpoints(EndpointIndexer.java:281)


	... 10 more

ERROR: jakarta.enterprise.inject.spi.DeploymentException: Non static nested resources classes are not supported: 'gr.cti.nts.keycloak.idp.social.gsis.GsisAbstractIdentityProvider$OIDCEndpoint'

ERROR: Non static nested resources classes are not supported: 'gr.cti.nts.keycloak.idp.social.gsis.GsisAbstractIdentityProvider$OIDCEndpoint'

For more details run the same command passing the '--verbose' option. Also you can use '--help' to see the details about the usage of the particular command.`

**Comment by evchristelis** [comment]
@XhmikosR @ktogias 
Did you had any change to check this?

**Comment by XhmikosR** [comment]
@vassilis-brachos-ed is this backwards compatible with older Keycloak? If so, can you please open a PR?

**Comment by XhmikosR** [comment]
NVM I just read Keycloak's source code. It's not backwards compatible. It seems this was introduced in v25.

Unless someone makes a PR which supports old environments, I'll need to make a new branch and pick your patch. Any help in the form of PRs is welcome. Even better if someone could add some kind of tests.

**Comment by Stratis-Dermanoutsos** [comment]
Should be resolved along with #120.
